### 1. GET All Doctors Filtered by Specialization

GET http://localhost:4004/odata/v4/hospital/Doctors?$filter=specialization eq 'Cardiologist'


### 2. GET Appointments for a Specific Date

GET http://localhost:4004/odata/v4/hospital/Appointments?$filter=appointmentDate eq 2026-03-01


### 3. POST a New Patient

POST http://localhost:4004/odata/v4/hospital/Patients
Content-Type: application/json

{
  "firstName": "Rohit",
  "lastName": "Mishra",
  "dateOfBirth": "1996-05-20",
  "gender": "Male",
  "bloodGroup": "O_POS",
  "phone": "9876600010",
  "email": "rohit@gmail.com",
  "address": "Bangalore",
  "emergencyContact": "9877700010",
  "registrationDate": "2026-03-10"
}


### 4. POST a New Appointment

POST http://localhost:4004/odata/v4/hospital/Appointments
Content-Type: application/json

{
  "appointmentDate": "2026-03-15",
  "appointmentTime": "10:30:00",
  "status": "Scheduled",
  "reason": "Routine Checkup",
  "notes": "First Visit",
  "fee": 1000,
  "patient_ID": "p1111111-1111-1111-1111-111111111111",
  "doctor_ID": "d1111111-1111-1111-1111-111111111111"
}


### 5. GET Patients Filtered by Blood Group

GET http://localhost:4004/odata/v4/hospital/Patients?$filter=bloodGroup eq 'O_POS'


### 6. PATCH Appointment Status to Completed

PATCH http://localhost:4004/odata/v4/hospital/Appointments(a1111111-1111-1111-1111-111111111111)
Content-Type: application/json

{
  "status": "Completed"
}